#!/bin/bash
# Скрипт перетворює всі файли з поточного каталогу що відповідають
# масці
files_to_work="*.css *.js *.html"
# додається до імені файле розширення '.h'
# При цьому у файлі створюється змінна з тим самим ім'ям(Деякі символи замінюються,
# щоб ім'я було валідним згідно правили Мови С)
Replase_mask=['.','-']
echo " Починаємо обробку файлів"
# будемо писати "центральний файл"
main_include="all_pages.h"
echo "Головний файл ${main_include} перезаписано"
echo "=========================================="
echo "#ifndef _ALL_PAGES_"> ${main_include}
echo "#define  _ALL_PAGES_">> ${main_include}
ALL_INCLUDES=""
ALL_CALL="#define SERVER_ON_ALL"
# Отримуємо масив файлів і почергово
for File_name in $(ls ${files_to_work}); 
do
    echo "---------------------------------------------------------"
    echo "Я знайшов файл $File_name. Починаю перетворення"
    out_file=${File_name}.h
    echo "Переписую файл $out_file."
    ALL_INCLUDES="${ALL_INCLUDES}#include \"$out_file\"\n" 
    # затираємо файл якщо він існує
    echo "// This file is automatically generated." > $out_file
    echo "// Please do not edit manually." >> $out_file
    echo "// Check the documentation to learn how to edit it" >> $out_file
    # пишемо гуард
    echo "#ifndef _${File_name//${Replase_mask}/_}_" >> $out_file
    echo "#define _${File_name//${Replase_mask}/_}_" >> $out_file
    echo "#include <ESP8266WebServer.h>" >> $out_file
    # створємо мави чарів
    echo "const char ${File_name//${Replase_mask}/_}[] PROGMEM = R\"=====(" >> $out_file
    # У який поміщаємо файл
    cat $File_name >> $out_file 
    echo -e ")=====\";\nextern ESP8266WebServer server;" >> $out_file
    # Створюємо функцію яка надсилатиме файло
    echo "void send_${File_name//${Replase_mask}/_}(){">> $out_file
    echo -e "\tdigitalWrite(D7, HIGH);">> $out_file
    echo -e "\tserver.send(200, \"text/${File_name##*.}\", ${File_name//${Replase_mask}/_});" >> $out_file
    echo -e "\tdigitalWrite(D7, LOW);">> $out_file
    echo "}" >> $out_file
    echo "#endif" >> $out_file
    echo "//EOF" >> $out_file
    ALL_CALL="${ALL_CALL} \ \n server.on(\"/${File_name}\",send_${File_name//${Replase_mask}/_});"
    # server.on("/style.css",send_style_css);
done
echo -e ${ALL_INCLUDES}>> ${main_include}

echo -e ${ALL_CALL}>> ${main_include}
echo >> ${main_include}
echo "#endif">> ${main_include}
echo "=========================================="

